export const phoneNumberRegex = /^\+\d{3} \d{2} \d{3} \d{2} \d{2}$/
export const minLength = 3
export const maxLength = 30
export const minEmailLength = 6
export const changePasswordAttempts = 3
export const reTryTime = 60000 * 30
export const stepEmail = 1
export const stepPhone = stepEmail
export const stepCode = 2
